controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['base_link_left_wheel_frontside', 'base_link_left_wheel_backside']
    right_wheel_names: ['base_link_right_wheel_frontside', 'base_link_right_wheel_backside']
    wheel_separation: 0.4
    wheel_radius: 0.05

    use_stamped_vel: false

# joint_broad:
#   ros__parameters:
