<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="dimensions.xacro" />

<link name="$(arg robot_name)imu_link">

  <visual>
    <geometry>
      <box size="0.05 0.05 0.05"/>
    </geometry>
  </visual>

  <xacro:inertial_box mass="0.0" x="0.0" y="0.0" z="0.0">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_box>

</link>

<joint name="$(arg robot_name)imu_joint" type="fixed">
  <parent link="$(arg robot_name)base_link"/>
  <child link="$(arg robot_name)imu_link"/>
  <!-- origin xyz="0.47 -0.15 0.05"  rpy="0 0 0"/ -->  <!-- 47.5 = 100/2 - 5/2: size of robot and sensor, so sensor is at front -->
  <origin xyz="0.0 0.0 ${wheel_radius/2.}"  rpy="0 0 0" />
</joint>

  <gazebo reference="$(arg robot_name)imu_link">
    <sensor name="imu_sensor" type="imu">
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
          <namespace>$(arg namespace)/imu</namespace>
          <remapping>~/out:=$(arg namespace)/imu</remapping>
        </ros>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
        <frame_name>$(arg robot_name)imu_link</frame_name>
      </plugin>
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <visualize>true</visualize>
     <imu>
        <magnetic_field>
            <x>
            <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1e-6</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
            </noise>
            </x>
            <y>
            <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1e-6</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
            </noise>
            </y>
            <z>
            <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1e-6</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
            </noise>
            </z>
        </magnetic_field>
     	<angular_velocity>
     	  <x>
     	    <noise type="gaussian">
                <stddev>2e-4</stddev>
                <mean>0.0</mean>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
                <stddev>2e-4</stddev>
                <mean>0.0</mean>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
                <stddev>2e-4</stddev>
                <mean>0.0</mean>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </z>
        </angular_velocity>

        <linear_acceleration>
            <x>
                <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                    <bias_mean>0.0005</bias_mean>
                    <bias_stddev>0.00001</bias_stddev>
                </noise>
            </x>
            <y>
                <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                    <bias_mean>0.0005</bias_mean>
                    <bias_stddev>0.00001</bias_stddev>
                </noise>
            </y>
            <z>
                <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                    <bias_mean>0.0005</bias_mean>
                    <bias_stddev>0.00001</bias_stddev>
                </noise>
            </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

</robot>