<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="colors.xacro" />
    <xacro:include filename="dimensions.xacro" />

    <!-- xacro:property name="base_width" value="0.62"/>
    <xacro:property name="base_length" value="1.0"/>
    <xacro:property name="base_height" value="0.1"/>

    <xacro:property name="wheel_radius" value="0.25" />
    <xacro:property name="wheel_length" value="0.1" />
    <xacro:property name="wheel_color_name" value="wheel_red" />
    <xacro:property name="wheel_color_rgb" value="1 0 0 1" />
    <xacro:property name="wheel_zoff" value="0.08"/ -->

    <xacro:macro name="body_link" params="name size_x size_y size_z color color_rgb mass" >
        <link name="$(arg robot_name)${name}">
            <visual>
                <geometry>
                    <box size="${size_x} ${size_y} ${size_z}"/>
                    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                </geometry>
                
                <material name="${color}">
                    <color rgba="${color_rgb}"/>
                </material>
            </visual>
            <collision>
                <!-- origin xyz="${mass_x/2} ${mass_y/2} ${mass_z/2}" rpy="0 0 0"/ -->
                <geometry>
                    <box size="${size_x} ${size_y} ${size_z}"/>
                    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="${mass}" x="${size_x}" y="${size_y}" z="${size_z}">
                <!-- origin xyz="${base_width/2} ${base_length/2} ${base_height/2}" rpy="0 0 0"/ -->
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            </xacro:inertial_box>
          
        </link>
   
    </xacro:macro>

<xacro:macro name="wheel" params="name mass wheel_radius">
    <link name="$(arg robot_name)${name}">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                <!-- mesh filename="file:///$(find nav25d_03)/description/meshes/wheel.stl"
                    scale="0.01 0.01 0.01" /-->
            </geometry>
            <material name="${wheel_color_name}">
                <color rgba="${wheel_color_rgb}"/>
            </material>
        </visual>
        <visual name="mark_visual">
            <geometry>
                <cylinder radius="${wheel_radius/2}" length="${wheel_length}" />
            </geometry>
            <material name="${wheel_color_name}_mark">
                <color rgba="1 1 1 1"/>
            </material>
            <origin xyz="${wheel_radius/2} 0 0" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="blue"/>
            <surface>
                <friction>
                    <ode>
                        <mu1 value="1.0"/>
                        <mu2 value="1.0"/>
                    </ode>
                </friction>
            </surface>
        </collision>
        <xacro:inertial_cylinder mass="${mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
</xacro:macro>

    <!-- xacro:macro name="wheel" params="name mass">
        <link name="$(arg robot_name)${name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <material name="${wheel_color_name}">
                    <color rgba="${wheel_color_rgb}"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
                <material name="blue"/>
            </collision>
            <xacro:inertial_cylinder mass="${mass}" length="${wheel_length}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link> 
    </xacro:macro -->

    <xacro:macro name="wheel_joint" params="name parent child xyz ">
        <joint name="$(arg robot_name)${name}" type="continuous">
            <parent link="$(arg robot_name)${parent}" />
            <child link="$(arg robot_name)${child}" />
            <origin xyz="${xyz}" rpy="${-pi/2} 0 0"/>
            <axis rpy="0 0 0" xyz="0 0 1"/>
            <!-- limit effort="1" velocity="1"/ -->
            <joint_properties damping="2.0" friction="0.01"/>
        </joint>
    </xacro:macro>   

    <!-- Robot Description -->

    <xacro:body_link name="base_link" size_x="${base_length}" size_y="${base_width}" size_z="${base_height}"
        color="$(arg robot_material_name)" color_rgb="$(arg robot_material_color_rgb)" 
        mass="1.0"/> 

   <!-- Robot Footprint -->
   <xacro:body_link name="base_footprint" size_x="0.0" size_y="0.0" size_z="0.0" color="green" color_rgb="0 1 0 1" 
        mass="0.0"/>

  <joint name="$(arg robot_name)base_joint" type="fixed">
    <parent link="$(arg robot_name)base_link"/>
    <child link="$(arg robot_name)base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>
    
    <xacro:wheel name="right_wheel_frontside" mass="0.1" wheel_radius="${wheel_radius}"/>
    <xacro:wheel_joint name="base_link_right_wheel_frontside" parent="base_link" 
        child="right_wheel_frontside" xyz="${wheel_radius+0.05} -0.4 ${wheel_zoff}" />

    <xacro:wheel name="right_wheel_backside" mass="0.1" wheel_radius="${wheel_radius}"/>
    <xacro:wheel_joint name="base_link_right_wheel_backside" parent="base_link" 
        child="right_wheel_backside" xyz="${-wheel_radius-0.05} -0.4 ${wheel_zoff}" />

    <xacro:wheel name="left_wheel_frontside" mass="0.1" wheel_radius="${wheel_radius}"/> 
    <xacro:wheel_joint name="base_link_left_wheel_frontside" parent="base_link" 
        child="left_wheel_frontside" xyz="${wheel_radius+0.05} 0.4 ${wheel_zoff}" />

    <xacro:wheel name="left_wheel_backside" mass="0.1" wheel_radius="${wheel_radius}"/> 
    <xacro:wheel_joint name="base_link_left_wheel_backside" parent="base_link" 
        child="left_wheel_backside" xyz="${-wheel_radius-0.05} 0.4 ${wheel_zoff}" />

    <!-- Gazebo Colors -->
    <gazebo reference="$(arg robot_name)base_link">
        <material>Gazebo/$(arg robot_material_name)</material>
    </gazebo>
    <gazebo reference="$(arg robot_name)right_wheel_frontside">
        <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="$(arg robot_name)right_wheel_backside">
        <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="$(arg robot_name)left_wheel_frontside">
        <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="$(arg robot_name)left_wheel_backside">
        <material>Gazebo/Red</material>
    </gazebo>

</robot>

